name: docker

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]


jobs:
  build-docker-image:

    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4


      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false 
          tags: pert-estimator-tool:test
